[package]
name = "ytsub"
version = "0.5.0"
edition = "2021"
description = "A subscriptions only TUI Youtube client"
authors = ["Berke Enercan <berkeenercan@tutanota.com>"]
repository = "https://github.com/sarowish/ytsub"
license = "GPL-3.0"
readme = "README.md"
keywords = ["youtube", "cli", "tui", "terminal"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.95"
clap = "4.5.23"
crossterm = "0.28.1"
dirs = "5.0.1"
futures-util = "0.3.31"
num_cpus = "1.16.0"
rand = "0.8.5"
rusqlite = "0.32.1"
webbrowser = "1.0.3"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
tokio = { version = "1.42.0", features = ["time", "macros", "rt-multi-thread"] }
tokio-util = "0.7.13"
ureq = { version = "2.12.1", features = ["json"] }
unicode-width = "0.2.0"
unicode-segmentation = "1.12.0"
toml = "0.8.19"
lazy_static = "1.5.0"
csv = "1.3.1"
quick-xml = { version = "0.37.2", features = ["serialize"] }
chrono = "0.4.39"
dyn-clone = "1.0.17"
parking_lot = "0.12.3"
ratatui = "0.29.0"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.29.0", features = ["process", "fs"] }

[features]
bundled_sqlite = ["rusqlite/bundled"]

[profile.release-lto]
inherits = "release"
lto = true
