[package]
name = "ytsub"
version = "0.6.0"
edition = "2024"
description = "A subscriptions only TUI Youtube client"
authors = ["Berke Enercan <berkeenercan@tutanota.com>"]
repository = "https://github.com/sarowish/ytsub"
license = "GPL-3.0"
readme = "README.md"
keywords = ["youtube", "cli", "tui", "terminal"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.98"
clap = "4.5.40"
crossterm = { version = "0.29.0", features = ["event-stream"] }
dirs = "6.0.0"
futures-util = "0.3.31"
num_cpus = "1.17.0"
rand = "0.9.1"
rusqlite = "0.36.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["time", "macros", "rt-multi-thread", "process"] }
tokio-util = "0.7.15"
unicode-width = "0.2.0"
unicode-segmentation = "1.12.0"
toml = "0.8.23"
csv = "1.3.1"
quick-xml = { version = "0.38.0", features = ["serialize"] }
chrono = "0.4.41"
dyn-clone = "1.0.19"
ratatui = "0.29.0"
regex-lite = "0.1.6"
reqwest = { version = "0.12.22", default-features = false, features = ["json", "rustls-tls", "gzip"] }
async-trait = "0.1.88"
open = "5.3.2"

[target.'cfg(unix)'.dependencies]
libc = "0.2.174"

[target.'cfg(windows)'.dependencies]
rusqlite = { version = "0.36.0", features = ["bundled"]}

[features]
bundled_sqlite = ["rusqlite/bundled"]


[profile.release-lto]
inherits = "release"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
