[package]
name = "ytsub"
version = "0.4.0"
edition = "2021"
description = "A subscriptions only TUI Youtube client that uses the Invidious API"
authors = ["Berke Enercan <berkeenercan@tutanota.com>"]
repository = "https://github.com/sarowish/ytsub"
license = "GPL-3.0"
readme = "README.md"
keywords = ["youtube", "cli", "tui", "terminal"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.69"
clap = "4.1.4"
crossterm = "0.26.0"
dirs = "4.0.0"
futures-util = "0.3.26"
num_cpus = "1.15.0"
rand = "0.8.5"
rusqlite = "0.28.0"
webbrowser = "0.8.7"
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.115"
tokio = { version = "1.25.0", features = ["time", "macros", "rt-multi-thread"] }
tokio-util = "0.7.4"
tui = { version = "0.19.0", default-features = false, features = ['crossterm'] }
ureq = { version = "2.6.2", features = ["json"] }
unicode-width = "0.1.10"
unicode-segmentation = "1.10.1"
toml = "0.7.1"
lazy_static = "1.4.0"
csv = "1.1.6"
quick-xml = { version = "0.27.1", features = ["serialize"] }
chrono = "0.4.23"
dyn-clone = "1.0.10"
parking_lot = "0.12.3"

[target.'cfg(unix)'.dependencies]
nix = "0.26.2"

[features]
bundled_sqlite = ["rusqlite/bundled"]

[profile.release-lto]
inherits = "release"
lto = true
