name: Nix

on:
  push:

jobs:
  build:
    name: Build flake
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - uses: cachix/cachix-action@v17
        with:
          name: ytsub
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build
        run: nix build -L
